### ISSUE TITLE
Browser specific pseudo classes end up in the output regardless whether they're used or not

### ISSUE THREAD

**Issue by viktorkelemen** [giakki/uncss#140]
I'm not sure this is the expected behaviour.

Consider the following

```js
uncss('<html>/<html>', {
  raw: 'input:-ms-input-placeholder { color: #000; }'
}, function (error, output) {
  // it includes input:-ms-input-placeholder although the html does not have input tags
  console.log(output);
});
```

The output includes input:-ms-input-placeholder although the html does not have input tags.
It behaves that same with other browser prefixes.

**Comment by ben-eb** [comment]
I think this is expected behaviour. Currently, UnCSS does not strip selectors that have pseudo classes/elements on them (for example, `h1:hover`) as it cannot test for this behaviour. Selectors such as these are therefore included regardless of whether the original element exists in the DOM.

I would agree however that instead of testing that the rule contains these selectors, UnCSS should understand which parts of the selector it can ignore; so that when testing `h1:hover` it could actually test `h1` instead. Then it could strip the rule if it didn't find any `h1` elements in the DOM.

I noticed this behaviour before in https://github.com/giakki/uncss/issues/74#issuecomment-67982080

**Comment by giakki** [comment]
Yeah, that is the issue.
Thanks @ben-eb.
