### ISSUE TITLE
Switch to PostCSS

### ISSUE THREAD

**Issue by XhmikosR** [giakki/uncss#153]
/CC @giakki @ben-eb

**Comment by ben-eb** [comment]
@giakki Are you interested in switching over to PostCSS? I'd be happy to develop this feature, it would also be nice if I could get collaborator access. But I think we need some kind of refactoring to happen also; the problem is that many of the function calls for UnCSS have APIs that are tightly integrated into each other. I would only be happy to do a parser rewrite if it meant that the bulk of the module was rewritten to be less coupled together. That should also help with an event based architecture for reporting as I previously suggested.

@XhmikosR What do you think of the current codebase? There are things in there that I don't think UnCSS should be handling, such as displaying error messages for CSS (https://github.com/giakki/uncss/blob/master/src/utility.js#L136-L172 - just let the error be thrown from the parser), or removing empty selectors/keyframes (https://github.com/giakki/uncss/blob/master/src/lib.js#L100-L134 - broadens module scope too widely, I wrote PostCSS alternatives), and again the reporting I feel should be delegated to other modules, much like https://github.com/substack/tape is just a test runner whose output can be consumed by other reporting modules.

I think it is in our best interests to scope UnCSS's responsibilities to DOM traversal and finding unused CSS selectors that way, and then encourage people to use it in a PostCSS context alongside other dedicated tools such as https://github.com/ben-eb/cssnano for best results. Therefore we should also look at deprecating a lot of the existing auxiliary functionality and do a `1.0.0` release.

**Comment by XhmikosR** [comment]
Don't get me wrong, but Git and GitHub don't really require collaborator status unless one needs to handle releases too. Or there are no other people to handle your contributions, but that's a future reference anyway.

As for the rest, sure they can be removed if the parser does things right and has a similar functionality.

As for cssnano, I'll personally keep using clean-css which is still [better in compression and speed](http://goalsmashers.github.io/css-minification-benchmark/) and more mature. It lacks other stuff but that's not for this issue.

That being said, I'd definitely be interested in a PR for this to see how things work. I expect it to be better than now, but that's just an assumption at this point.

**Comment by giakki** [comment]
I'm back working on uncss, sorry for the long wait.
This looks like a great place to start. I'll start the transition on a new branch, so you can review / add changes on it.

Cheers!

**Comment by tonai** [comment]
Hi !
Any news about the postcss transition ?
Thanks,

**Comment by dbkaplun** [comment]
+1

**Comment by doodzik** [comment]
+1

**Comment by stubailo** [comment]
This would make it much easier to use this plugin with Meteor.

**Comment by XhmikosR** [comment]
Fixed in recent patches by @mikelambert !

**Comment by RyanZim** [comment]
Is there a way to use uncss as a postcss plugin?

**Comment by mikelambert** [comment]
Yes, that's what the patch mentioned in this issue fixed. If you look at the code for https://github.com/giakki/uncss/blob/master/src/uncss.js

You will see that it exports a variable called postcssPlugin:
var uncss = require('uncss');
uncss.postssPlugin({html: [...]})
