### ISSUE TITLE
SyntaxError: Parse error with gulp-uncss

### ISSUE THREAD

**Issue by seffw** [giakki/uncss#217]
Hoping someone can offer some ideas on this one. This is one of those 'I wouldn't believe it is i hadn't seen it'

This is on a Windows 7 x64 system with the latest versions of node, npm, gulp and gulp-uncss.

Having used gulp-uncss successfully on different projects, it is now creating a 'SyntaxError: Parse error' when running the gulp script (and I've isolated down to this being the cause).

I've uninstallled / reinstalled, and also updated gulp itself and not sure what to do as the code in the gulpfile is unchanged (from successful uses). 

Is there any way to find out what is causing this error? A Google search suggested  this might be related to Phantonjs but no relevant links or anyone with this issue are shown.

I'm not sure how to fix it, when it was not changed since in a working state, and the error doesn't describe where the issue is coming from.

Any help would be greatly appreciated.

**Comment by mikelambert** [comment]
Can you paste the relevant lines of your gulpfile? Is this an issue of needing to add .on('error', console.log) to get better error messages from gulp pipelines?

**Comment by simplyeffectiveweb** [comment]
Hi. Here's the part of the script (two version, tried both, exactly same results):

`.pipe(uncss({
	html: [sitepath + '/layouts/**/*.html'],
	ignore: [/--/,/.in/]
	}, function(err, output) {
			if (err) {
				gutil.log(err)
			}
	}
))`

and

`.pipe(uncss({
	html: [sitepath + '/layouts/**/*.html'],
	ignore: [/--/,/.in/]
	}
))`


I have been trying to think what could have change from when it was working. The script hasn't (first version), i hadn't updated any node or gulp modules or plug-ins. Of course other things changed (the html and css files it is using), but all other pre-processing is working ok (css minification, useref) which happen after in this script.

How would i best add the .on('error' ...... here? I can try this.

**Comment by mikelambert** [comment]
Add it to the just before or just after the .pipe(...). I'm a bit unsure on the gulp semantics, myself.

**Comment by simplyeffectiveweb** [comment]
I tried it at the start and end of the pipe. The script ran (so i guess i put the code in ok) but the same error without more info showed

**Comment by mikelambert** [comment]
Sorry it didn't help.

Without a repro case, not much to go on. My only remaining suggestion is to start chucking out large chunks of HTML/CSS until the error goes away, and then binary-tree search adding/removing chunks until you figure out what's triggering the error and have a small repro case.

**Comment by simplyeffectiveweb** [comment]
I appreciate it's a bit of a strange one. 

I'm just testing one other thing. One change I made previously was to use relative rather than absolute paths. Although it worked ok after change to a relative path before, i've just tried one test with absolute path and it may have worked. I mean this if it needs more expanation:

`.pipe(uncss({ html: [sitepath +`

i had sitepath simply as 'site' (the relative location to where the gulp sccript was called from, which I'm using throughout the gulp script),   now trying the C:\.........\site  instead. 

Does this highlight some obvious error in how I might be using relative paths?

(I read somewhere that uncss performed better with relative paths)

**Comment by mikelambert** [comment]
I don't have access to a windows box to test with.

One possibility: We use npm's glob.sync(), and according to the documentation on https://github.com/isaacs/node-glob , it has some issues regarding backslashes. Not sure how that would play out in your relative vs absolute scenario.

Without a repro case, I suspect you're going to have to dig into your node_modules/uncss/src/uncss.js' getHTML or other functions to add logging and figure out exactly what's going on.

**Comment by simplyeffectiveweb** [comment]
Ok, I'll keep trying and report back

**Comment by simplyeffectiveweb** [comment]
To update, I found the part of the HTML files that was causing the error. I don't why this is the case though.

This is it (id details replaced with ####): 

```
<div id="wrapper" class="content">
    <script src="http://www.booking.com/general.html?tmpl=bookit;aid=#####;lang=en;hotel_id=######;hotel_cc1=en;hotel_page=#######"></script>
</div>
```

If I change the SRC to some local js file, the error is not shown. So it's the SRC as is causing it.

Two potential bugs here are 1) that the syntax error is preventing uncss working correctly (it seems to be stopping at that point).  2)  that this type of use of a script tag is not so uncommon

**Comment by mikelambert** [comment]
Uncss uses the phantom web browser to render web pages and figure out which css selectors are actually used. Yeah, a javascript error could interrupt things, same as a normal web page flow.

As far as why the above script src is giving you a Parse Error, it should support remote js without any issues. I suspect there's a problem with the actual contents of the js file, that the phantom (webkit) browser isn't parsing.

More thoughts for you:
- Are you sure the file you are including is a js file? It appears to be general.html, which is suspicious.
- Are you sure the js file you are including is valid js without parse errors? You didn't include the ### numbers, so I can't verify for myself.
- Have you tried downloading the booking.com js file, and referencing that locally instead of remotely? Does it still give the same error?

**Comment by RyanZim** [comment]
@simplyeffectiveweb ping?

**Comment by RyanZim** [comment]
@seffw Is this still an issue for you?

**Comment by seffw** [comment]
Sorry for late reply. I've been busy with other things. I'll try to re-test this soon and willl report back

**Comment by RyanZim** [comment]
@seffw ping?

**Comment by RyanZim** [comment]
@seffw ping?

**Comment by RyanZim** [comment]
@seffw ping?

**Comment by RyanZim** [comment]
@mikelambert This looks abandoned IMO, can you close?
