### ISSUE TITLE
If a JS library adds CSS when triggered, would it be removed if not in the DOM at runtime?

### ISSUE THREAD

**Issue by jasondavis** [giakki/uncss#221]
Sorry if my question is covered I dint research much.

I am curious, often JavaScript apps will add CSS classes when events trigger them to be needed.  Is there any practical way for this app to detect that those should stay/remain even though they might not be present in the DOM when this runs?

I realize there might not be a real perfect solution here but perhaps there is above my knowledge level?

**Comment by aseem2625** [comment]
I've the same question.

My gulp-uncss configuration is
   
    gulp.task('uncssme', function () {

    return gulp.src('src/css/**/*.css')
        .pipe(uncss({
            html: ['src/**/*.html']
        }))
        .pipe(gulp.dest('dist/css'))
       });

And I am adding a 'newClass' through javascript
    document.getElementById('good').className += ' newClass';

But by 'newClass' selector is getting removed from CSS file because it is not used directly in html files.
Please, add a way to add parse js files to rectify this problem.

I am already using,

    /* uncss:ignore */
    .newClass {
      background-color: blue;
    }

But it is bad practice to mention this ignore comment every time I dynamically add a class.

**Comment by mikelambert** [comment]
So if the JS is added at startup as part of page render, the browser will detect the CSS classes, and UnCSS will keep them. If they are only added in response to events, then UnCSS has no way to detect that they could be added. Trying to do this automatically is essentially an impossible task.

As another potential avenue for a solution here, you could generate a "yourwebpage.html#RunForUnCSS" of sorts (or if it doesn't work, we should add support for such a feature), where your chose of debug flags triggers all your requisite javascript handlers to add all the relevant CSS classes you like in the rendered page, so that UnCSS will retain those classes in the generated CSS.

I'm going to mark this as closed. Please see #244 if you're curious why this is impossible to analyze JS code automatically in the general case.

**Comment by aseem2625** [comment]
@mikelambert We've more use cases for adding the class dynamically (using js) on events than adding classes through js in the beginning. Just think, how much useful is this latter part in real world web applications? Not much. Most applications have former part because that is why people want to use js to add classes dynamically on event happening. I was thinking, if we can have some js parser which takes into consideration some rules like wherever addClass, className, id, etc. are found then those classes/ids much be kept in css files. What say?

**Comment by mikelambert** [comment]
Yes, there are many reasons why you'd use js to add classes after the page loads. I in fact use many in my own projects as well. And yup, it'd be much more useful if you could handle that all automatically, too!

Unfortunately, you seem to miss that this is a very difficult task to do, and impossible to do correctly. You can add a js parser, and you can check for addClass and other similar names. But how deep do you want to go? For example, even this relatively straightforward code would fail to work:

function handleToggle(obj, visibleClass, invisibleClass) {
  if (obj.something) {
    obj.addClass(visibleClass);
    obj.removeClass(invisibleClass);
  } else {
    obj.addClass(invisibleClass);
    obj.removeClass(visibleClass);
  }
}
handleVisibility(h1, 'main-visible', 'main-invisible');
handleVisibility(h2, 'secondary-visible', 'secondary-invisible');

And any debug CSS classes you use would get caught by such a parser and kept:
if (debug) {
  obj.addClass('debugClass');
}
...when you actually don't want something like that in production.

Or as another example, even bootstrap JS runs a lot of code to add/remove classes, most of which you might never use/call, but that would trigger those bootstrap CSS classes to be kept around, as a result of the bootstrap JS.


So yeah...I provided a workaround in the above post. If you don't like that workaround, you're welcome to tackle it yourself. You'd have to integrate a javascript parser (and trying to figure out how to work that into the webdriver-based approach the system uses), and make it an optional component (due to the false-positives and false-negatives described above). Good luck!

**Comment by aseem2625** [comment]
You're correct that false-positive cases might get added. So, currently, I am fine with using ignore: [regex] to collectively ignore all the classes added with js(regex because, I've made prefix as ".jsa-newClass" for every class/selector added through js.) This helps for css I would create. But for compression of Bootstrap or other vendor files, I think it's better to use other gulp plugin like purifycss if it helps get it done. But anyways, thank you to give insights.
