### ISSUE TITLE
Am I really supposed to ignore every dynamic style?

### ISSUE THREAD

**Issue by cameronroe** [giakki/uncss#227]
Do I really need to add an array of selectors for every single dynamic style added to my site? What if it's a massive site? This isn't really ideal. Is there anyway to bulk ignore all dynamic styles?

**Comment by mikelambert** [comment]
Essentially, yes.

How would you recommend the Uncss code know that it's a dynamic style?

Maybe if you prefix all dynamic styles with "dynamic-", it will also make it easy to make a regex selector to ignore all such styles. Does that work?

**Comment by cameronroe** [comment]
Yeah, anything is better than manually adding it in for the plugin. It should be built into a convention or something like that. I also have no clue what's even getting added a runtime. Ideally there could be a diff configuration that evals the js on the page and diffs the selectors from each other.

**Comment by mikelambert** [comment]
It doesn't need to be built-into a convention, since you can just make your own convention. Prefix everything with "my-dynamic-prefix-", and then add that single RegExp("my-dynamic-prefix") to your list of ignores. Boom, now you have your own convention.

Currently, it actually does eval the js on the page, along with rendering all the html content, in an attempt to figure out what css is used. So any CSS that is stuck into fields at page startup will be detected as "used". (So if you want, that is another way to force UnCSS to see things as "used"). The problem with dynamic content, is that it requires user-input to trigger the use of the content, and our PhantomJS web browser cannot click everything on the page in all combinations, just hoping to exercise all your code paths.

**Comment by RyanZim** [comment]
@mikelambert Any reason for this to be open?
