### ISSUE TITLE
postcss-uncss

### ISSUE THREAD

**Issue by RyanZim** [giakki/uncss#236]
This relates to #153.

uncss can be used as a postcss plugin, however, since the plugin is exported under `.postcssPlugin`, it cannot be used from postcss-cli (postcss-cli only takes package names and expects the packages to directly export the plugin).

I am currently running a js file that uses the postcss API directly; but that's an unpleasant workaround.

Are there plans to make uncss more easy to use as a postcss plugin? (I realize this is still in development)

**Comment by mikelambert** [comment]
It'd be nice to export it directly, but I believe it would break all existing users of uncss who depend on the default export being the older styled function (and not the postcss plugin).

We could create a new wrapper npm project called postcss-uncss that exported it directly, which is probably the least invasive approach?

Or we could assume that the by-far-largest user of uncss is gulp-uncss, and fix that to access the function and ensure a seamless cutover for those users, and just break everyone else on a major upgrade.

I can't tell the absolute number of raw uncss users, but they are dwarfed by gulp-uncss, as evidenced by the distribution of these searches:

all js files containing 'require' and 'uncss': https://github.com/search?l=javascript&q=require+uncss&ref=searchresults&type=Code&utf8=%E2%9C%93

all json (ie package.json) files containing 'uncss': https://github.com/search?l=json&q=uncss&ref=searchresults&type=Code&utf8=%E2%9C%93

**Comment by RyanZim** [comment]
I'm in favor of a wrapper project.

**Comment by RyanZim** [comment]
@mikelambert Any idea when the next version of uncss will be released?

**Comment by mikelambert** [comment]
@RyanZim , do you want to create/publish/own that wrapper NPM?

And no idea about uncss releases, I believe that is @giakki's call. I don't have any permissions there.

**Comment by RyanZim** [comment]
@mikelambert I'll get that wrapper together as soon as I can. Should I add any of y'all as collaborators?

About releases, I was just wondering since the postcss plugin hasn't been shipped yet (I'll have to use a GitHub endpoint for the dependencies).

**Comment by RyanZim** [comment]
@mikelambert In writing the docs, I'm not sure exactly what options the plugin accepts. I would assume:

- html
- ignore
- timeout

What about `uncssrc`?

I haven't tried any of them yet.

**Comment by mikelambert** [comment]
You're looking at the options for the standalone binary.

Looking at the actual plugin itself, https://github.com/giakki/uncss/blob/master/src/uncss.js#L255

I'd say the options were:
- ignoreSheets: WARNING: since we are often running a pipeline with postcss where the stylesheet is passed in, we shouldn't really be overriding ignoreSheets at all...I'd omit this option in any docs.
- html: the list of filenames to check when filtering the incoming postcss css
- ignore: The list of strings or RegExps (though it's probably impossible to pass a RegExp in a commandline UI, so effectively this is strings-only for now, unless the wrapper handles that via // detection or something)

**Comment by RyanZim** [comment]
OK thanks, just wasn't sure if any other options were available. I agree that `ignoreSheets` shouldn't be in the docs. 


> though it's probably impossible to pass a RegExp in a commandline UI

If you're referring to postcss-cli, I'm using a json config file for the options, so they would be escaped anyhow.

**Comment by RyanZim** [comment]
@mikelambert After uncss ships the postcss plugin as part of an official release, how do you think would be the best way to version postcss-uncss in relation to uncss's version number?

**Comment by RyanZim** [comment]
Here it is:

https://github.com/RyanZim/postcss-uncss

:tada: :tada: :tada: :tada: :tada:

**Comment by mikelambert** [comment]
Yay, thank you!

As far as versioning, I am unclear on best practices, or all of the possibilities in the npm ecosystem:
- hardcode the version, and keep them in sync. perhaps a PITA to update postcss-uncss version/dependency everytime we update uncss. (I don't like this)
- use a very liberal version dependency in package.json (that grabs the latest version of uncss), and therefore avoid having to update postcss-uncss. (I'm fine with this, I assume it just means we only require manual work when the uncss major version number changes.)
- use a peerDependency so that postcss-uncss doesn't depend on any version in particular (beyond what's required for compatibility), and enforces the importing package to define which version of uncss they want. (I feel like this probably gives the most control to someone wanting to work around uncss bugs/features/etc. So I think I might prefer this one, though I understand it introduces additional complexity to the caller's package.json to get things to work, and probably necessitates a bit of additional documentation.)

Any other ideas I miss?

**Comment by RyanZim** [comment]
@mikelambert I hadn't thought of a peerDependency, but that sounds good to me. Will look into that further.

**Comment by RyanZim** [comment]
@mikelambert One question: Is there a possibility that uncss might break backwards-compatibility in a patch version during the pre-v1.0.0 stage?

With a peerDependancy, I would probably keep the major (or minor during pre-v1.0.0) version the same as uncss.

**Comment by mikelambert** [comment]
It's possible? ...but you see us jumping through hoops here to make a postcss-uncss that doesn't break backwards-compatibility in the pre-v1.0.0 stage. :)

To be honest, the owner of this project is rather MIA, and there's no real active development on the project beyond what people contribute (such as my rewrite to use postcss). So given I don't know the next time we'll push an NPM version that could even break anything, so this may be a relatively moot discussion. So you can eel free to do what you like with your peer dependency that makes you the most comfortable.

**Comment by RyanZim** [comment]
OK, gotcha. I have a policy of bumping the minor when I break backwards-compat in pre-v1.0.0; but that isn't part of the SemVer, just my convention.

> To be honest, the owner of this project is rather MIA

:grinning: Perhaps he could add one of the collaborators here as an owner/collaborator on npm?

**Comment by RyanZim** [comment]
@mikelambert I added docs for usage as a postcss plugin to the README in #240.

**Comment by RyanZim** [comment]
@mikelambert If there are no objections, I think I'll start submitting postcss-uncss to the various lists of postcss plugins.

**Comment by mikelambert** [comment]
Go for it.

**Comment by mikelambert** [comment]
Also FYI, a few days ago I got NPM access, and pushed 0.14 to NPM just now. So may change the nature of bugs reported (hopefully improved!)

**Comment by RyanZim** [comment]
:tada: Can you make the changelog entry at https://github.com/giakki/uncss/releases?

**Comment by mikelambert** [comment]
Ahh good call, done.

**Comment by RyanZim** [comment]
@mikelambert I've got postcss-uncss updated in a branch, loading uncss 0.14.0 as a peerDependency.

Can you review it? Here is the link to the commit: https://github.com/RyanZim/postcss-uncss/commit/8331a567790f7a1289ac8fb0e60ec1e347d1d37f.

**Comment by RyanZim** [comment]
Done and published: https://github.com/RyanZim/postcss-uncss/releases/latest. :tada:
