### ISSUE TITLE
Install on RPi fails (ARM architecture)

### ISSUE THREAD

**Issue by jhpratt** [giakki/uncss#302]
It fails at phantonjs-prebuilt

Not sure why, or if you can even fix this (I doubt it's your package). It works as expected on my laptop, so I'll just have to copy the code over in the meantime.

**Comment by RyanZim** [comment]
@jhpratt This package relies on arch-specific PhantomJS binaries, contained in `phantomjs-prebuilt`. Coping code won't work since you need the correct binary for your platform.

There is an experimental fork of this project that uses jsdom instead of PhantomJS. This fork doesn't need binaries, so you might want to try it by installing `uncss-jsdom` instead of `uncss`. PR is here: https://github.com/giakki/uncss/pull/280

**Comment by mikelambert** [comment]
Uncss 0.15.0 just published, which removes the phantomjs dependency, and probably will fix your issue.

**Comment by RyanZim** [comment]
@mikelambert Can we close?
