### ISSUE TITLE
Replace or update chai-resemble

### ISSUE THREAD

**Issue by XhmikosR** [giakki/uncss#316]
chai-resemble is using phantom thus making the dependency tree pretty huge. We should look into alternative packages or update chai-resemble. 

/CC @giakki

**Comment by mikelambert** [comment]
Are our dependencies huge, or just our dev dependencies? I don't care as much about the latter...

**Comment by XhmikosR** [comment]
It's for devDependencies but it's really a useless dependency now with jsdom. I doubt @giakki will ever update chai-resemble so we should look into another way of achieving the same thing.

**Comment by XhmikosR** [comment]
Does anybody know any similar lib we can use instead of chai-resemble?

**Comment by mikelambert** [comment]
Yeah, I don't care about devDependencies. They are irrelevant to anyone using uncss. They only matters for people who are actively developing uncss, which at the moment is like...less than one? There are certainly much better things one can spend one's time on...

**Comment by RyanZim** [comment]
@mikelambert & I now have commit access to chai-resemble, who wants to update it?

**Comment by XhmikosR** [comment]
Would it be too hard to replace it with jsdom? Not sure if it's too much work, just thinking out loud. That would solve the https issue and the dep tree size.

**Comment by RyanZim** [comment]
@XhmikosR jsdom allows you to programmatically work with HTML & the DOM. jsdom can't actually perform a page render, though. The point of chai-resemble is to ensure that the page looks the same visually, so that requires an actual browser render.

If somebody wants to upgrade chai-resemble, I'm fine with it; chai-resemble is useful regardless of uncss using it or not. However, I'm wondering if uncss really needs these tests. Can't we just manually check for visual regressions and enforce that the CSS output stays the same?

**Comment by RyanZim** [comment]
I know it's a bit ugly, but I'm just gonna close this for the time being. Happy to revisit if someone wants to update chai-resemble.
