### ISSUE TITLE
`:focus-within` rules are removed, even if they are in the `ignore` list

### ISSUE THREAD

**Issue by davidmurdoch** [giakki/uncss#349]
If I have a rule such as:

`div:focus-within { background: red; }` it will be removed from the CSS by uncss. If I add `ignore: ["div:focus-within"]` to my uncss options, it still gets removed.

I've tracked down the root cause of the issue. The reason it is getting removed is because the `dePseudify` function thinks the rule is a match for `:focus` due to the nature of the regex used.

My short-term solution is to uppercase my rule in both my CSS and `ignore` list to `div:FOCUS-WITHIN`. Since this works, this probably implies that the `dePsuedify` function needs to use a case-insensitive flag for the regex matches.

p.s., thanks for this tool!

**Comment by RyanZim** [comment]
Dat `dePseudify` :grimacing: Attn @mikelambert @corpulentcoffee @joostlawerman

**Comment by corpulentcoffee** [comment]
I guess `dePseudify()` is everyone's favorite.

This particular issue might be caused by the lack of an end anchor (`$`) on the regex that is used in that function. In a CSS selector, can anything follow after a pseudo that would be negatively affected by having a `$` in the regex?

Sometimes I think that this function would be easier to reason about if instead of using a regex replace, it just walked the selector while checking to see if an escape is present (for #345) until it hits the first non-escaped colon, if any, and then drop everything off after it unless there's some special case (i.e. use a blacklist for items like those identified in https://github.com/giakki/uncss/pull/330#issuecomment-328698701 rather than a whitelist).

It would also be nice if `dePseudify()` was exported to be importable by the test suite to be tested directly independently... then we could just build up a bunch of test cases for this thing to make sure it's gotten right.

**Comment by RyanZim** [comment]
> Sometimes I think that this function would be easier to reason about if instead of using a regex replace, it just walked the selector while checking to see if an escape is present (for #345) until it hits the first non-escaped colon, if any, and then drop everything off after it unless there's some special case (i.e. use a blacklist for items like those identified in #330 (comment) rather than a whitelist).

Problem with that approach is that the CSS spec keeps adding items that would need on the blacklist.

> It would also be nice if dePseudify() was exported to be importable by the test suite to be tested directly independently... then we could just build up a bunch of test cases for this thing to make sure it's gotten right.

Agree 100% on that one.

Alternately, perhaps we should look into using https://github.com/postcss/postcss-selector-parser for this.

**Comment by corpulentcoffee** [comment]
> Alternately, perhaps we should look into using https://github.com/postcss/postcss-selector-parser for this.

I think this looks easier.

I've only barely glanced at this but something like https://github.com/giakki/uncss/compare/master...corpulentcoffee:depseudify-via-psp might work?

**Comment by RyanZim** [comment]
@corpulentcoffee Looking great, PR welcome.

---

I'm thinking as a separate fix for the original issue, we need to add `:focus-within` to the list of ignored pseudos, right?
