### ISSUE TITLE
ability to output the removed css rules.

### ISSUE THREAD

**Issue by enapupe** [giakki/uncss#49]
How do you look after what was removed? 
It would be nice a 'inverted' output, displaying what was removed, not what should be used. This way is easier to know when you have enough garbage to do something about.

**Comment by jepek** [comment]
+1

**Comment by sbeam** [comment]
this would be really useful as a way to generate a periodic report, not only usage %, but a list that designers could look over manually, since adding uncss as a post-compile workflow step won't work for us. Found the `report.selectors.unused` list easily enough and it looks good, but it won't make it through css.stringify without some more work (and not sure what is missing there :)

**Comment by ivanmayes** [comment]
+1, we have gone crazy a couple times trying to figure out why something didn't look right, would have been great to reference the removed styles.

**Comment by ben-eb** [comment]
@giakki What do you think of UnCSS being an event emitter, so that consumers can listen for events such as `style:removed`, `style:kept`, or `style:ignored`? Thus removing the responsibility of UnCSS to produce a report of used/unused styles, and instead extract that into a reporter module that can listen to these events and act on them.

I like this pattern in mocha. It means that you could have different reporters, even extracted into node modules themselves, to do different kinds of logging - a debug logger that logged all events, an unused logger that would only report unused CSS etc.

**Comment by giakki** [comment]
Ooh, that's a cool idea, I'll try and play around with it a little, and report back! :+1:

**Comment by AndyBean** [comment]
+1 to this great idea on reporting addition, understanding that it is perhaps contingent on other projects.

**Comment by ivanmayes** [comment]
Just wanted to link to someone doing this really well:
https://github.com/nDmitry/grunt-autoprefixer

they output a file.css.diff with the additions and changes for your css.  Might be something worth considering for this option.

**Comment by silvenon** [comment]
:+1: This would be such an awesome addition.

**Comment by malcomio** [comment]
Yes, for sites using CSS preprocessors and compiling as part of the deployment, a simple list of the irrelevant selectors would be fantastic.

**Comment by corysimmons** [comment]
+1

**Comment by gpszymczak** [comment]
:+1:

**Comment by corysimmons** [comment]
PurifyCSS can do this. Switched.

https://github.com/purifycss/purifycss/pull/62

**Comment by gpszymczak** [comment]
thanks @corysimmons

**Comment by corysimmons** [comment]
:+1:

**Comment by andersonbarutti** [comment]
+1

**Comment by corysimmons** [comment]
PurifyCSS can do this: https://github.com/purifycss/purifycss#options-optional

**Comment by RyanZim** [comment]
@mikelambert is this fixed? See #200.
