### ISSUE TITLE
What about css class dynamically added by some javascript ?

### ISSUE THREAD

**Issue by maiis** [giakki/uncss#5]
If in my JS, i have:

``` javascript
$(this).addClass('new-class');
```

How will it be interpreted by uncss ?

**Comment by josenobile** [comment]
Hello, 

Maybe this will look as a support request.

I use jQuery UI (modal), the "dismissable" functionality stopped working. Also this: http://mynameismatthieu.com/WOW/ stopped working.

To find the selectors that are being removed I inspect the HTML elements (Chrome  Developer tools) finding the CSS style tab and compare the full CSS against the uncss version. However for this two libraries I was unable to find any difference using this method.

Is there a better way to detect the missing CSS that are affecting the functionality of the website?

**Comment by drschwabe** [comment]
Just thinking aloud, it would be nice simply to have the option to pass/parse a JS file for any mention of CSS classes ie- make it detect and include the CSS class in this example: 

`uncss -parseJS 'myscript.js' > styles.css`

Where myscript.js has say 300 lines of code, with one such line being: 

`$('#some-selector').addClass('.my-cool-class')`

and as such, `.my-cool-class` is included in the final output styles.css

You wouldn't need any JS logic specifically; just cross reference any ".class-names" with what is in the source CSS files and if there is a match include it; otherwise don't include it; ie- it's not CSS; avoid false negatives

**Comment by RyanZim** [comment]
@drschwabe That's easier said than done without any false positives. https://github.com/purifycss/purifycss does something similar to this.
