### ISSUE TITLE
UnCSS and absolute links

### ISSUE THREAD

**Issue by maxbucknell** [giakki/uncss#90]
Hi,

I am trying to test possible gains we might see from implementing UnCSS (with our CMS this would be a nontrivial optimisation), but the utility appears to be letting me down, although I'm sure I'm just using it wrong.

Running the command:

```
uncss http://made.com > stylesheet.css
```

results in the error

```
Error: UnCSS: no stylesheets found
    at uncss (/usr/local/lib/node_modules/uncss/lib/uncss.js:135:25)
    at fn (/usr/local/lib/node_modules/uncss/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/usr/local/lib/node_modules/uncss/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

which is unhelpful. I believe I'm following a prescribed use case, since this is the same command that is run against a bootstrap page in the readme. Magento uses absolute links (replete with a protocol) to link to assets, so I'm thinking it might be because of this?

Any help appreciated.

**Comment by giakki** [comment]
@maxbucknell sorry for the long wait.
It looks like PhantomJS "breaks" upon loading Prototype.js. Removing it from the URL (`http://www.made.com/it/minify/1416234427/js...`) fixes the problem.

I'll keep investigating, but unfortunately there isn't much I can do about that, since PhantomJS does not even report any errors.

**Comment by maxbucknell** [comment]
That's bizarre. I will check what you say, but if that's true, I'd cheerfully strip JavaScript and leave stylesheets in there.

Thank you so much for figuring this out. I wouldn't have known where to start, so I'd appreciate a description of how you did it (assuming it wasn't just trying random stuff). If you're too busy, then don't worry.

**Comment by giakki** [comment]
No problem!

To test it, since you said removing the `<head>` was enough, I tried removing each script. Luckily, the one in question was number 3.
Seeing that it was made of different paths, I tried removing each part, and again, out of luck, removing the first part was enough (I also tried removing other parts just to be sure I wasn't crazy, but only Prototype was troublesome).

Again, it's pretty hard to debug the real issue, since PhantomJS reports nothing.

**Comment by RyanZim** [comment]
@maxbucknell Is this still an issue?

**Comment by redboxdigital-m2** [comment]
@RyanZim Not for me. I mean, it's an issue for someone, somewhere, but @giakki pointed out a workaround that was sufficient for me.

Are you doing a cleanup, or something? Happy for this to be closed.

**Comment by maxbucknell** [comment]
@RyanZim Not for me. I mean, it's an issue for someone, somewhere, but @giakki pointed out a workaround that was sufficient for me.

Are you doing a cleanup, or something? Happy for this to be closed.
