### ISSUE TITLE
Feature Request: Add option for only one newline between CSS rule sets

### ISSUE THREAD

**Issue by 1951FDG** [giakki/uncss#93]
An option to specify only one newline between CSS rule sets would be great. Useful in diffs, e.g., comparing a JS Beautifier processed CSS file and a UnCSS processed CSS file.

Also see, https://github.com/beautify-web/js-beautify/issues/528

**Comment by ben-eb** [comment]
I'm not sold on adding this to UnCSS, I think it detracts from the scope of the module, which is to provide a CSS file that has been cleaned of unused selectors, and I would guess that most people's use cases for that CSS is to run it through a minifier and then put it into production.

For your diff example you can always try running both files through a beautifier and comparing them that way. In fact this is probably better because then the code is formatted consistently in both versions.

**Comment by 1951FDG** [comment]
This issue can be closed!

**Comment by 1951FDG** [comment]
This issue can be closed! This enhancement is covered at https://github.com/beautify-web/js-beautify/pull/574 pull request.

**Comment by RyanZim** [comment]
@giakki @XhmikosR @mikelambert could you close this as per @1951FDG?
